[book]
authors = ["Rollup Boost Core Contributors"]
language = "en"
multilingual = false
src = "book"
title = "Rollup Boost Book"
description = "A book on how rollup-boost works"

[output.html]
theme = "book/theme"
git-repository-url = "https://github.com/flashbots/rollup-boost"
default-theme = "ayu"
no-section-label = true

[output.html.fold]
enable = true
level = 1

[build]
build-dir = "target/book"